name: vitally
description: Hybrid Mobile Application for Nutrition Recommendation and Tracking

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  smooth_page_indicator:
  email_validator:
  flushbar:
  shared_preferences: ^0.5.10
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  modal_progress_hud:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/onBoarding/1.png
    - assets/images/onBoarding/2.png
    - assets/images/onBoarding/3.png
    - assets/images/dashBoard/
    - assets/images/Login/login.png
    - assets/images/Login/signUp.png
    - assets/images/Login/google.png
    - assets/images/registration/
    - assets/images/updating/
    - assets/logo/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-semiBold.ttf
        - asset: assets/fonts/Montserrat-semiBoldItalic.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
